#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_warn
#' @importFrom cli format_inline
#' @importFrom cli qty
#' @importFrom htmltools tagList
#' @importFrom methods formalArgs
#' @importFrom methods functionBody
#' @importFrom rlang as_label
#' @importFrom rlang caller_arg
#' @importFrom rlang caller_env
#' @importFrom rlang current_call
#' @importFrom rlang current_env
#' @importFrom rlang enquos
#' @importFrom rlang eval_tidy
#' @importFrom rlang local_error_call
#' @importFrom rlang names2
#' @importFrom rlang try_fetch
#' @importFrom S7 class_any
#' @importFrom S7 class_character
#' @importFrom S7 class_data.frame
#' @importFrom S7 class_Date
#' @importFrom S7 class_factor
#' @importFrom S7 class_function
#' @importFrom S7 class_integer
#' @importFrom S7 class_list
#' @importFrom S7 class_logical
#' @importFrom S7 class_numeric
#' @importFrom S7 class_POSIXt
#' @importFrom S7 method<-
#' @importFrom S7 methods_register
#' @importFrom S7 new_class
#' @importFrom S7 new_generic
#' @importFrom S7 new_property
#' @importFrom S7 new_S3_class
#' @importFrom S7 S7_class
#' @importFrom S7 S7_dispatch
#' @importFrom S7 S7_inherits
#' @importFrom S7 S7_object
#' @importFrom S7 set_props
#' @importFrom shiny dateInput
#' @importFrom shiny dateRangeInput
#' @importFrom shiny NS
#' @importFrom shiny numericInput
#' @importFrom shiny observe
#' @importFrom shiny radioButtons
#' @importFrom shiny reactiveValues
#' @importFrom shiny selectInput
#' @importFrom shiny selectizeInput
#' @importFrom shiny sliderInput
#' @importFrom shiny textAreaInput
#' @importFrom shiny textInput
#' @importFrom shiny updateDateInput
#' @importFrom shiny updateDateRangeInput
#' @importFrom shiny updateNumericInput
#' @importFrom shiny updateRadioButtons
#' @importFrom shiny updateSelectInput
#' @importFrom shiny updateSelectizeInput
#' @importFrom shiny updateSliderInput
#' @importFrom shiny updateTextAreaInput
#' @importFrom shiny updateTextInput
#' @importFrom tidyselect eval_select
#' @importFrom utils modifyList
## usethis namespace: end
NULL
